### PR TITLE
Add Solaris support

### PR DESCRIPTION
**Pull request by bgermann**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like CI is red though?

**Comment by bgermann** [comment]
Yes, because there is no prebuilt image yet. Can you please build and provide it?

**Comment by bgermann** [comment]
I have included its Dockerfile.

**Comment by alexcrichton** [comment]
Mind publishing it yourself? I'd personally rather not be on the hook for maintaining these images

**Comment by bgermann** [comment]
Okay.

**Pull request merged**
